kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
# create a cluster with the local registry enabled in containerd
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5101"]
    endpoint = ["http://kind-registry:5000"]
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /proc
        containerPath: /proc-host
      - hostPath: /usr/src
        containerPath: /usr/src
    extraPortMappings:
    - containerPort: 30090
      hostPort: 9090