apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: push-s3
spec:
  workspaces:
  - name: mnt
    persistentVolumeClaim:
      claimName: task-pvc
  params:
  - name: COS_PROVIDER
    value: ibmcloud
  - name: COS_SECRET_NAME
    value: ibm-cos-secret
  taskRef:
    name: ibmcloud-s3-push