version: 2
updates:
  - package-ecosystem: pip
    directory: /dockerfiles/requirements.txt
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily