namespace: kepler

patchesStrategicMerge:
- ./patch/patch-estimator-sidecar.yaml
- ./patch/patch-model-server.yaml
- ./patch/patch-openshift.yaml

resources:
- ../kepler
- ../server
- ./openshift/scc.yaml
