receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets:
              - app:8100

processors:
  batch:
    timeout: 3s

exporters:
  logging:
    loglevel: debug
  #otlp/metrics:
  #  endpoint: "api.honeycomb.io:443"
  #  headers:
  #    "x-honeycomb-team": '${API_KEY}'
  #    "x-honeycomb-dataset": '${HONEYCOMB_DATASET}'
extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [logging]
      #exporters: [logging, otlp/metrics]


