apiVersion: v1
kind: ConfigMap
metadata:
  name: kepler-model-server-cfm
  namespace: kepler
data:
  PROM_SERVER: 'http://prometheus-k8s.monitoring.svc.cluster.local:9090'
  PROM_QUERY_INTERVAL: '20'
  PROM_QUERY_STEP: '3'
  PROM_HEADERS: ''
  PROM_SSL_DISABLE: 'true'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepler-model-server
  namespace: kepler
spec:
  template:
    spec:
      containers:
      - name: server-api
      - name: online-trainer
        image: kepler_model_server
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: cfm
            mountPath: /etc/kepler/kepler.config
            readOnly: true
          - name: mnt
            mountPath: /mnt
            readOnly: false
        command: [ "python3.8" ]
        args: ["-u", "src/train/online_trainer.py" ]
