apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cpe.cogadvisor.io/v1","kind":"Benchmark","metadata":{"annotations":{},"name":"coremark","namespace":"default"},"spec":{"benchmarkOperator":{"name":"none","namespace":"default"},"benchmarkSpec":"parallelism: 1\nbackoffLimit: 0\ntemplate:\n  spec:\n    containers:\n      - name: coremark\n        image: ghcr.io/sunya-ch/coremark:ubi\n        env:\n        - name: THREADNUM\n          value: \"4threads\"\n        command:\n        - sh\n        - -c\n        - ./coremark-${THREADNUM}.exe\n    restartPolicy: Never\n","iterationSpec":{"iterations":[{"location":".template.spec.containers[0].env[name=THREADNUM].value","name":"t","values":["8threads","16threads","32threads"]},{"location":".parallelism","name":"parallelism"}],"sequential":true},"parserKey":"coremark","repetition":3}}
  creationTimestamp: "2023-02-24T03:50:45Z"
  finalizers:
  - finalizers.benchmark.cpe.cogadvisor.io
  generation: 1
  name: coremark
  namespace: default
  resourceVersion: "19171250"
  uid: aa96504f-b5fc-4f5f-b742-a31fb2c3311b
spec:
  benchmarkOperator:
    name: none
    namespace: default
  benchmarkSpec: |
    parallelism: 1
    backoffLimit: 0
    template:
      spec:
        containers:
          - name: coremark
            image: ghcr.io/sunya-ch/coremark:ubi
            env:
            - name: THREADNUM
              value: "4threads"
            command:
            - sh
            - -c
            - ./coremark-${THREADNUM}.exe
        restartPolicy: Never
  iterationSpec:
    iterations:
    - location: .template.spec.containers[0].env[name=THREADNUM].value
      name: t
      values:
      - 8threads
      - 16threads
      - 32threads
    - location: .parallelism
      name: parallelism
    sequential: true
  parserKey: coremark
  repetition: 3
status:
  bestResults:
  - build: init
    configurations: {}
    performanceKey: iterations_per_sec
    performanceValue: "72410.104501"
    scenarioID: parallelism=1;t=8threads
  - build: init
    configurations: {}
    performanceKey: iterations_per_sec
    performanceValue: "143680.218810"
    scenarioID: parallelism=1;t=16threads
  - build: init
    configurations: {}
    performanceKey: iterations_per_sec
    performanceValue: "283506.219377"
    scenarioID: parallelism=1;t=32threads
  - build: init
    configurations: {}
    performanceKey: iterations_per_sec
    performanceValue: "37402.244135"
    scenarioID: parallelism=1;t=4threads
  hash:
  - build: init
    hash: "152377304"
    iterations:
      parallelism: "1"
      t: 8threads
    run: "0"
  - build: init
    hash: "385258259"
    iterations:
      parallelism: "1"
      t: 16threads
    run: "0"
  - build: init
    hash: "2615945765"
    iterations:
      parallelism: "1"
      t: 32threads
    run: "0"
  - build: init
    hash: "1209626772"
    iterations:
      parallelism: "1"
      t: 4threads
    run: "0"
  - build: init
    hash: "169154923"
    iterations:
      parallelism: "1"
      t: 8threads
    run: "1"
  - build: init
    hash: "368480640"
    iterations:
      parallelism: "1"
      t: 16threads
    run: "1"
  - build: init
    hash: "2599168146"
    iterations:
      parallelism: "1"
      t: 32threads
    run: "1"
  - build: init
    hash: "1226404391"
    iterations:
      parallelism: "1"
      t: 4threads
    run: "1"
  - build: init
    hash: "185932542"
    iterations:
      parallelism: "1"
      t: 8threads
    run: "2"
  - build: init
    hash: "418813497"
    iterations:
      parallelism: "1"
      t: 16threads
    run: "2"
  - build: init
    hash: "2582390527"
    iterations:
      parallelism: "1"
      t: 32threads
    run: "2"
  - build: init
    hash: "1243182010"
    iterations:
      parallelism: "1"
      t: 4threads
    run: "2"
  jobCompleted: 12/12
  results:
  - build: init
    configID: ""
    configurations: {}
    repetitions:
    - job: coremark-cpeh-152377304
      performanceKey: iterations_per_sec
      performanceValue: "72410.104501"
      pod: coremark-cpeh-152377304-fwrtk
      pushedTime: 2023-02-24 03:51:04.939973507 +0000 UTC m=+165170.561865635
      run: "0"
    - job: coremark-cpeh-169154923
      performanceKey: iterations_per_sec
      performanceValue: "71789.851526"
      pod: coremark-cpeh-169154923-cr6hd
      pushedTime: 2023-02-24 03:52:16.15403602 +0000 UTC m=+165241.775928132
      run: "1"
    - job: coremark-cpeh-185932542
      performanceKey: iterations_per_sec
      performanceValue: "71655.402655"
      pod: coremark-cpeh-185932542-dmq5j
      pushedTime: 2023-02-24 03:53:26.391766446 +0000 UTC m=+165312.013658557
      run: "2"
    scenarioID: parallelism=1;t=8threads
    scenarios:
      parallelism: "1"
      t: 8threads
  - build: init
    configID: ""
    configurations: {}
    repetitions:
    - job: coremark-cpeh-385258259
      performanceKey: iterations_per_sec
      performanceValue: "142256.708697"
      pod: coremark-cpeh-385258259-pgb5f
      pushedTime: 2023-02-24 03:51:22.98304711 +0000 UTC m=+165188.604939248
      run: "0"
    - job: coremark-cpeh-368480640
      performanceKey: iterations_per_sec
      performanceValue: "143112.701252"
      pod: coremark-cpeh-368480640-z2tj2
      pushedTime: 2023-02-24 03:52:33.72603419 +0000 UTC m=+165259.347926301
      run: "1"
    - job: coremark-cpeh-418813497
      performanceKey: iterations_per_sec
      performanceValue: "145671.246482"
      pod: coremark-cpeh-418813497-n9ltj
      pushedTime: 2023-02-24 03:53:43.725429385 +0000 UTC m=+165329.347321530
      run: "2"
    scenarioID: parallelism=1;t=16threads
    scenarios:
      parallelism: "1"
      t: 16threads
  - build: init
    configID: ""
    configurations: {}
    repetitions:
    - job: coremark-cpeh-2615945765
      performanceKey: iterations_per_sec
      performanceValue: "280903.359668"
      pod: coremark-cpeh-2615945765-6s6ms
      pushedTime: 2023-02-24 03:51:41.053349028 +0000 UTC m=+165206.675241142
      run: "0"
    - job: coremark-cpeh-2599168146
      performanceKey: iterations_per_sec
      performanceValue: "286109.079086"
      pod: coremark-cpeh-2599168146-vfzgp
      pushedTime: 2023-02-24 03:52:51.284075248 +0000 UTC m=+165276.905967424
      run: "1"
    - job: coremark-cpeh-2582390527
      performanceKey: iterations_per_sec
      performanceValue: "274186.010282"
      pod: coremark-cpeh-2582390527-mkjf7
      pushedTime: 2023-02-24 03:54:02.535204953 +0000 UTC m=+165348.157097087
      run: "2"
    scenarioID: parallelism=1;t=32threads
    scenarios:
      parallelism: "1"
      t: 32threads
  - build: init
    configID: ""
    configurations: {}
    repetitions:
    - job: coremark-cpeh-1209626772
      performanceKey: iterations_per_sec
      performanceValue: "37402.244135"
      pod: coremark-cpeh-1209626772-5c96t
      pushedTime: 2023-02-24 03:51:58.094088103 +0000 UTC m=+165223.715980261
      run: "0"
    - job: coremark-cpeh-1226404391
      performanceKey: iterations_per_sec
      performanceValue: "36968.576710"
      pod: coremark-cpeh-1226404391-k4h6g
      pushedTime: 2023-02-24 03:53:08.331569734 +0000 UTC m=+165293.953461850
      run: "1"
    - job: coremark-cpeh-1243182010
      performanceKey: iterations_per_sec
      performanceValue: "36990.332072"
      pod: coremark-cpeh-1243182010-8h84b
      pushedTime: 2023-02-24 03:54:19.58798405 +0000 UTC m=+165365.209876160
      run: "2"
    scenarioID: parallelism=1;t=4threads
    scenarios:
      parallelism: "1"
      t: 4threads
