apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc
  namespace: default
spec:
  storageClassName: manual
  volumeName: task-pv-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi