version: "3"
services:
  prometheus:
    image: prom/prometheus
    ports: 
      - "9091:9090"
    command: [--config.file=/etc/prometheus/prometheus.yaml]
    volumes: 
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
  
  
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension

  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.weights
    depends_on:
      - prometheus
    ports:
      - "8100:8100"
    entrypoint: 

        python3 server.py

    
