apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cpe.cogadvisor.io/v1","kind":"Benchmark","metadata":{"annotations":{},"name":"coremark","namespace":"default"},"spec":{"benchmarkOperator":{"name":"none","namespace":"default"},"benchmarkSpec":"parallelism: 1\nbackoffLimit: 0\ntemplate:\n  spec:\n    containers:\n      - name: coremark\n        image: ghcr.io/sunya-ch/coremark:ubi\n        env:\n        - name: THREADNUM\n          value: \"4threads\"\n        command:\n        - sh\n        - -c\n        - ./coremark-${THREADNUM}.exe\n    restartPolicy: Never\n","iterationSpec":{"iterations":[{"location":".template.spec.containers[0].env[name=THREADNUM].value","name":"t","values":["8threads","16threads","32threads"]},{"location":".parallelism","name":"parallelism"}],"sequential":true},"parserKey":"coremark","repetition":3}}
  creationTimestamp: "2023-02-24T03:36:22Z"
  finalizers:
  - finalizers.benchmark.cpe.cogadvisor.io
  generation: 1
  name: coremark
  namespace: default
  resourceVersion: "19168969"
  uid: fd5b6bb5-cb2d-41ce-af9b-b9561e60a942
spec:
  benchmarkOperator:
    name: none
    namespace: default
  benchmarkSpec: |
    parallelism: 1
    backoffLimit: 0
    template:
      spec:
        containers:
          - name: coremark
            image: ghcr.io/sunya-ch/coremark:ubi
            env:
            - name: THREADNUM
              value: "4threads"
            command:
            - sh
            - -c
            - ./coremark-${THREADNUM}.exe
        restartPolicy: Never
  iterationSpec:
    iterations:
    - location: .template.spec.containers[0].env[name=THREADNUM].value
      name: t
      values:
      - 8threads
      - 16threads
      - 32threads
    - location: .parallelism
      name: parallelism
    sequential: true
  parserKey: coremark
  repetition: 3
status:
  bestResults:
  - build: init
    configurations: {}
    performanceKey: iterations_per_sec
    performanceValue: "147748.848072"
    scenarioID: parallelism=1;t=8threads
  - build: init
    configurations: {}
    performanceKey: iterations_per_sec
    performanceValue: "289419.478189"
    scenarioID: parallelism=1;t=16threads
  - build: init
    configurations: {}
    performanceKey: iterations_per_sec
    performanceValue: "547507.699327"
    scenarioID: parallelism=1;t=32threads
  - build: init
    configurations: {}
    performanceKey: iterations_per_sec
    performanceValue: "73850.132188"
    scenarioID: parallelism=1;t=4threads
  hash:
  - build: init
    hash: "152377304"
    iterations:
      parallelism: "1"
      t: 8threads
    run: "0"
  - build: init
    hash: "385258259"
    iterations:
      parallelism: "1"
      t: 16threads
    run: "0"
  - build: init
    hash: "2615945765"
    iterations:
      parallelism: "1"
      t: 32threads
    run: "0"
  - build: init
    hash: "1209626772"
    iterations:
      parallelism: "1"
      t: 4threads
    run: "0"
  - build: init
    hash: "169154923"
    iterations:
      parallelism: "1"
      t: 8threads
    run: "1"
  - build: init
    hash: "368480640"
    iterations:
      parallelism: "1"
      t: 16threads
    run: "1"
  - build: init
    hash: "2599168146"
    iterations:
      parallelism: "1"
      t: 32threads
    run: "1"
  - build: init
    hash: "1226404391"
    iterations:
      parallelism: "1"
      t: 4threads
    run: "1"
  - build: init
    hash: "185932542"
    iterations:
      parallelism: "1"
      t: 8threads
    run: "2"
  - build: init
    hash: "418813497"
    iterations:
      parallelism: "1"
      t: 16threads
    run: "2"
  - build: init
    hash: "2582390527"
    iterations:
      parallelism: "1"
      t: 32threads
    run: "2"
  - build: init
    hash: "1243182010"
    iterations:
      parallelism: "1"
      t: 4threads
    run: "2"
  jobCompleted: 12/12
  results:
  - build: init
    configID: ""
    configurations: {}
    repetitions:
    - job: coremark-cpeh-152377304
      performanceKey: iterations_per_sec
      performanceValue: "146395.022569"
      pod: coremark-cpeh-152377304-dnhc5
      pushedTime: 2023-02-24 03:36:49.554647945 +0000 UTC m=+164315.176540026
      run: "0"
    - job: coremark-cpeh-169154923
      performanceKey: iterations_per_sec
      performanceValue: "147094.876195"
      pod: coremark-cpeh-169154923-gtb4b
      pushedTime: 2023-02-24 03:38:35.776245335 +0000 UTC m=+164421.398137419
      run: "1"
    - job: coremark-cpeh-185932542
      performanceKey: iterations_per_sec
      performanceValue: "149756.645451"
      pod: coremark-cpeh-185932542-kpjdk
      pushedTime: 2023-02-24 03:40:23.018894399 +0000 UTC m=+164528.640786483
      run: "2"
    scenarioID: parallelism=1;t=8threads
    scenarios:
      parallelism: "1"
      t: 8threads
  - build: init
    configID: ""
    configurations: {}
    repetitions:
    - job: coremark-cpeh-385258259
      performanceKey: iterations_per_sec
      performanceValue: "280554.094336"
      pod: coremark-cpeh-385258259-bjz5h
      pushedTime: 2023-02-24 03:37:16.6031656 +0000 UTC m=+164342.225057779
      run: "0"
    - job: coremark-cpeh-368480640
      performanceKey: iterations_per_sec
      performanceValue: "298284.862043"
      pod: coremark-cpeh-368480640-nk6nk
      pushedTime: 2023-02-24 03:39:01.83371383 +0000 UTC m=+164447.455605919
      run: "1"
    - job: coremark-cpeh-418813497
      performanceKey: iterations_per_sec
      performanceValue: "285748.303369"
      pod: coremark-cpeh-418813497-lqv7c
      pushedTime: 2023-02-24 03:40:50.07443985 +0000 UTC m=+164555.696331934
      run: "2"
    scenarioID: parallelism=1;t=16threads
    scenarios:
      parallelism: "1"
      t: 16threads
  - build: init
    configID: ""
    configurations: {}
    repetitions:
    - job: coremark-cpeh-2615945765
      performanceKey: iterations_per_sec
      performanceValue: "547507.699327"
      pod: coremark-cpeh-2615945765-7nmz7
      pushedTime: 2023-02-24 03:37:43.669243929 +0000 UTC m=+164369.291136063
      run: "0"
    - job: coremark-cpeh-2599168146
      performanceKey: iterations_per_sec
      performanceValue: "513753.612330"
      pod: coremark-cpeh-2599168146-tnhts
      pushedTime: 2023-02-24 03:39:30.903961018 +0000 UTC m=+164476.525853101
      run: "1"
    - job: coremark-cpeh-2582390527
      performanceKey: iterations_per_sec
      performanceValue: "539325.842697"
      pod: coremark-cpeh-2582390527-wmjdp
      pushedTime: 2023-02-24 03:41:18.141209877 +0000 UTC m=+164583.763101958
      run: "2"
    scenarioID: parallelism=1;t=32threads
    scenarios:
      parallelism: "1"
      t: 32threads
  - build: init
    configID: ""
    configurations: {}
    repetitions:
    - job: coremark-cpeh-1209626772
      performanceKey: iterations_per_sec
      performanceValue: "72555.777254"
      pod: coremark-cpeh-1209626772-7bm5j
      pushedTime: 2023-02-24 03:38:09.720881647 +0000 UTC m=+164395.342773729
      run: "0"
    - job: coremark-cpeh-1226404391
      performanceKey: iterations_per_sec
      performanceValue: "74608.306391"
      pod: coremark-cpeh-1226404391-wntw4
      pushedTime: 2023-02-24 03:39:56.960762335 +0000 UTC m=+164502.582654419
      run: "1"
    - job: coremark-cpeh-1243182010
      performanceKey: iterations_per_sec
      performanceValue: "74386.312918"
      pod: coremark-cpeh-1243182010-kd5xb
      pushedTime: 2023-02-24 03:41:43.703014852 +0000 UTC m=+164609.324906946
      run: "2"
    scenarioID: parallelism=1;t=4threads
    scenarios:
      parallelism: "1"
      t: 4threads
