# example-abs-train-pipeline:
#   running pipelines with all default value to train AbsPower model (intel_rapl, BPFOnly)
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-retrain-ibmcloud
spec:
  timeouts:
    pipeline: "6h"
    tasks: "5h50m"
  workspaces:
  - name: mnt
    persistentVolumeClaim:
      claimName: task-pvc
  params:
  - name: PIPELINE_NAME
    value: AbsPowerTrainPipelineExample
  - name: OUTPUT_TYPE
    value: AbsPower
  pipelineRef:
    name: single-retrain-pipeline