# test-collect
#   short run of pipelines to test collecting data
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-collect
spec:
  timeouts:
    pipeline: "6h"
    tasks: "5h50m"
  workspaces:
  - name: mnt
    persistentVolumeClaim:
      claimName: task-pvc
  params:
  - name: MACHINE_ID
    value: test
  - name: STRESS_ARGS
    value:
    - "cpu;none;none"
  - name: STRESS_TIMEOUT
    value: 20
  - name: STRESS_BREAK_INTERVAL
    value: 1
  - name: IDLE_COLLECT_INTERVAL
    value: 100
  - name: CPU_FREQUENCY_ENABLED
    value: false
  pipelineRef:
    name: collect-data-pipeline