apiVersion: v1
kind: ConfigMap
metadata:
  name: kepler-model-server-cfm-demo
  namespace: monitoring
data:
  MODEL_PATH: '../demo/models'
  PROM_SERVER: 'http://prometheus-k8s.monitoring.svc.cluster.local:9090'
  PROM_QUERY_INTERVAL: '20'
  PROM_QUERY_STEP: '3'
  PROM_HEADERS: ''
  PROM_SSL_DISABLE: 'true'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepler-model-server
  namespace: monitoring
  labels:
    app.kubernetes.io/component: model-server-demo
    app.kubernetes.io/name: kepler-model-server-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: model-server-demo
      app.kubernetes.io/name: kepler-model-server-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/component: model-server-demo
        app.kubernetes.io/name: kepler-model-server-demo
    spec:
      volumes:
      - name: cfm
        configMap:
          name: kepler-model-server-cfm-demo
      containers:
      - name: server-api
        image: quay.io/sustainable_computing_io/kepler_model_server_demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        volumeMounts:
          - name: cfm
            mountPath: /etc/kepler/kepler.config
            readOnly: true
---
kind: Service
apiVersion: v1
metadata:
  name: kepler-model-server-demo
  namespace: monitoring
  labels:
    app.kubernetes.io/component: model-server-demo
    app.kubernetes.io/name: kepler-model-server-demo
spec:
  selector:
    app.kubernetes.io/component: model-server-demo
    app.kubernetes.io/name: kepler-model-server-demo
  ports:
  - name: http
    port: 9000
    targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: model-server-demo
    app.kubernetes.io/name: kepler-model-server-demo
  name: kepler-model-server-demo
  namespace: monitoring
spec:
  endpoints:
  - interval: 3s
    port: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: model-server-demo
      app.kubernetes.io/name: kepler-model-server-demo