name: Build-Push Kepler Model Server Image

on:
  workflow_call:
    secrets:
      docker_username:
        description: 'Docker username'
        required: false
      docker_password:
        description: 'Docker password'
        required: false
    inputs:
      base_change:
        description: 'Change flag on base image'
        required: true
        type: string
      image_repo:
        description: 'The image repo to use'
        required: true
        type: string
      image_tag:
        description: 'The image tag to use'
        required: true
        type: string
      push:
        description: 'Push image'
        required: false
        type: string
        default: false


env:
  base_change: ${{ inputs.base_change }}
  base_image: ${{ inputs.image_repo }}/kepler_model_server_base:${{ inputs.image_tag }}
  image: ${{ inputs.image_repo }}/kepler_model_server:${{ inputs.image_tag }}

jobs:

  check-secret:
    runs-on: ubuntu-latest

    outputs:
      available: ${{ steps.check-secret.outputs.available }}

    steps:
      - name: Check Secret
        id: check-secret
        env:
          SECRET: ${{ secrets.docker_password }}
        run: |
          if [ "$SECRET" == "" ]; then
              echo "available=false" >> "$GITHUB_OUTPUT"
          else
              echo "available=true" >> "$GITHUB_OUTPUT"
          fi


  check-base-exist:
    runs-on: ubuntu-latest

    outputs:
      exists: ${{ steps.check-base-exist.outputs.exists }}

    steps:
    - name: Check if Docker base image exists
      id: check-base-exist
      run: |
        if docker pull ${{ env.base_image }}; then
              echo "exists=true" >> "$GITHUB_OUTPUT"
        else
              echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

  build:
    runs-on: ubuntu-latest
    needs: [check-secret, check-base-exist]
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker
      if: ${{ needs.check-secret.outputs.available == 'true' }} 
      uses: docker/login-action@v3
      with:
          registry: ${{ inputs.image_repo }}
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}    
    - name: Build-push base image
      if: ${{ (needs.check-secret.outputs.available == 'true') && ((needs.check-base-exist.outputs.exists == 'false') || (env.base_change == 'true')) }} 
      uses: docker/build-push-action@v5
      with:
        context: dockerfiles
        platforms: linux/amd64
        push: true
        tags: ${{ env.base_image }}
        file: dockerfiles/Dockerfile.base
    - name: Replace value in file
      if: ${{ (needs.check-secret.outputs.available == 'true') && ((needs.check-base-exist.outputs.exists == 'false') || (env.base_change == 'true')) }} 
      run: |
        sed -i "s|quay.io/sustainable_computing_io/kepler_model_server_base:v0.7|${{ env.base_image }}|" dockerfiles/Dockerfile
    - name: Build-push image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: ${{ inputs.push }}
        tags: ${{ env.image }}
        file: dockerfiles/Dockerfile
