name: Train Power Model on Self-hosted Runner

on:
  push:
    branches:
      - v*-release

jobs:
  train-model:

    strategy:
      matrix:
        instance_type: [c6i.metal, i3.metal]

    uses: ./.github/workflows/train-model-self-hosted.yml
    with:
      instance_type: ${{ matrix.instance_type }}
      ami_id: 'ami-0e4d0bb9670ea8db0'
      github_repo: ${{ github.repository }}
    secrets:
      self_hosted_github_token: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      security_group_id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
