on:
  push:
  pull_request:

jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}-daemon
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Test
        run: make build-test
      - name: Test pipeline
        run: make test-pipeline
      - name: Test model server
        run: make test-model-server
      - name: Test estimator
        run: make test-estimator
        timeout-minutes: 5